
language: java


addons:
  apt:
    packages:
      - oracle-java8-installer
 

jdk:
  - oraclejdk8
  
 script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7 
  
