
language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
 "before_install":
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
  - oraclejdk8
  
 script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7 
  
